//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod bir araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü: 4.0.30319.42000
//
//     Bu dosyada yapılan değişiklikler yanlış davranışa yol açabilir ve şu durumda kaybolur
//     kod yeniden oluşturulduğunda.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReaLTaiizor_CR.Properties
{


    /// <summary>
    ///   Yerelleştirilmiş dizeleri vs. aramak için türü kesin belirlenmiş bir kaynak sınıfı.
    /// </summary>
    // Bu sınıf, StronglyTypedResourceBuilder tarafından otomatik olarak
    // ResGen ya da Visual Studio gibi bir araç ile oluşturuldu.
    // Bir üye eklemek ya da kaldırmak için .ResX dosyanızı düyenleyin, sonra da ResGen
    // öğesini /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden derleyin.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReaLTaiizor_CR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Geçerli iş parçacığının CurrentUICulture özelliğini, türü kesin belirlenmiş
        ///   bu kaynak sınıfını kullanan tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
